[[linked_paths]]
name = "gjhgj"
id = 1
path = 'C:\Users\pasna\Stepan\Code'

[[linked_paths]]
name = "ergerg"
id = 1
path = 'C:\Users\pasna\Stepan'

[[linked_paths]]
name = "sffd"
id = 1
path = 'C:\Users\pasna\Stepan'
